#!/usr/bin/env python3
"""Build the OING decorative UI atlas from approved and generated sources."""

from __future__ import annotations

import json
from pathlib import Path

from PIL import Image, ImageDraw


ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = ROOT / "design" / "ui-atlas"
SOURCE_SHEET = OUT_DIR / "source" / "decor-sheet-transparent.png"
ATLAS_PATH = OUT_DIR / "oing-ui-atlas.png"
MAP_PATH = OUT_DIR / "oing-ui-atlas-map.json"
CSS_PATH = OUT_DIR / "oing-ui-atlas.css"
ATLAS_SIZE = (2048, 2048)


DECOR_CROPS = {
    "stage-ribbon": ((41, 214, 446, 396), (420, 120)),
    "stage-arch-panel-deco": ((487, 80, 929, 497), (420, 230)),
    "cloud-left": ((980, 139, 1178, 266), (190, 100)),
    "cloud-right": ((994, 332, 1200, 470), (190, 100)),
    "item-dock-base-deco": ((67, 614, 1188, 791), (1200, 260)),
    "speech-bubble-frame": ((54, 910, 545, 1175), (620, 180)),
    "bottom-flower-ground-deco": ((631, 964, 1196, 1139), (620, 190)),
}


PLACEMENTS = {
    "stage-ribbon": (32, 34),
    "stage-arch-panel-deco": (480, 24),
    "cloud-left": (930, 42),
    "cloud-right": (1140, 42),
    "badge-circle-deco": (1360, 32),
    "coin-icon": (1510, 24),
    "paw-icon": (1670, 24),
    "star-icon": (1830, 24),
    "item-dock-base-deco": (32, 300),
    "speech-bubble-frame": (1260, 288),
    "bottom-flower-ground-deco": (1260, 512),
    "hint-icon": (32, 760),
    "shuffle-icon": (224, 760),
    "bomb-icon": (416, 760),
    "clock-icon": (608, 760),
    "cat-character": (850, 720),
}


EXISTING_ASSETS = {
    "hint-icon": (ROOT / "assets/icons/items/hint.webp", (160, 160)),
    "shuffle-icon": (ROOT / "assets/icons/items/shuffle.webp", (160, 160)),
    "bomb-icon": (ROOT / "assets/icons/items/bomb.webp", (160, 160)),
    "clock-icon": (ROOT / "assets/icons/hud/time.webp", (160, 160)),
    "cat-character": (ROOT / "assets/characters/cat-peek.webp", (360, 310)),
    "coin-icon": (ROOT / "assets/icons/hud/score.webp", (140, 140)),
    "paw-icon": (ROOT / "assets/decor/paw.webp", (140, 140)),
    "star-icon": (ROOT / "assets/decor/star.webp", (140, 140)),
}


def alpha_crop(image: Image.Image) -> Image.Image:
    image = image.convert("RGBA")
    bbox = image.getchannel("A").getbbox()
    if not bbox:
        raise ValueError("source asset has no visible pixels")
    return image.crop(bbox)


def stretch(image: Image.Image, size: tuple[int, int]) -> Image.Image:
    return image.convert("RGBA").resize(size, Image.Resampling.LANCZOS)


def contain(image: Image.Image, size: tuple[int, int], padding: int = 8) -> Image.Image:
    source = alpha_crop(image)
    inner = (max(1, size[0] - padding * 2), max(1, size[1] - padding * 2))
    scale = min(inner[0] / source.width, inner[1] / source.height)
    resized = source.resize(
        (max(1, round(source.width * scale)), max(1, round(source.height * scale))),
        Image.Resampling.LANCZOS,
    )
    tile = Image.new("RGBA", size, (0, 0, 0, 0))
    tile.alpha_composite(resized, ((size[0] - resized.width) // 2, (size[1] - resized.height) // 2))
    return tile


def badge_circle(size: tuple[int, int] = (120, 120)) -> Image.Image:
    image = Image.new("RGBA", size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(image, "RGBA")
    inset = 8
    draw.ellipse((inset, inset + 5, size[0] - inset, size[1] - inset + 5), fill=(190, 57, 87, 125))
    draw.ellipse((inset, inset, size[0] - inset, size[1] - inset), fill=(244, 78, 111, 255), outline=(255, 244, 236, 255), width=7)
    draw.ellipse((24, 18, 80, 48), fill=(255, 180, 194, 155))
    draw.arc((18, 17, size[0] - 18, size[1] - 18), 205, 335, fill=(177, 45, 75, 145), width=4)
    return image


def sprite_css(entries: list[dict]) -> str:
    lines = [
        "/* Generated by build-atlas.py. */",
        ".oing-atlas-sprite {",
        '  background-image: url("./oing-ui-atlas.png");',
        "  background-repeat: no-repeat;",
        "  image-rendering: auto;",
        "}",
        "",
    ]
    aw, ah = ATLAS_SIZE
    for entry in entries:
        x, y, width, height = entry["x"], entry["y"], entry["width"], entry["height"]
        size_x = aw / width * 100
        size_y = ah / height * 100
        pos_x = 0 if aw == width else x / (aw - width) * 100
        pos_y = 0 if ah == height else y / (ah - height) * 100
        lines.extend(
            [
                f'.oing-atlas--{entry["name"]} {{',
                f"  background-size: {size_x:.6f}% {size_y:.6f}%;",
                f"  background-position: {pos_x:.6f}% {pos_y:.6f}%;",
                f"  aspect-ratio: {width} / {height};",
                "}",
                "",
            ]
        )
    return "\n".join(lines)


def main() -> None:
    if not SOURCE_SHEET.exists():
        raise FileNotFoundError(SOURCE_SHEET)

    source_sheet = Image.open(SOURCE_SHEET).convert("RGBA")
    sprites: dict[str, Image.Image] = {}
    sources: dict[str, str] = {}

    for name, (crop_box, size) in DECOR_CROPS.items():
        sprites[name] = stretch(source_sheet.crop(crop_box), size)
        sources[name] = str(SOURCE_SHEET.relative_to(ROOT))

    for name, (path, size) in EXISTING_ASSETS.items():
        if not path.exists():
            raise FileNotFoundError(path)
        sprites[name] = contain(Image.open(path), size)
        sources[name] = str(path.relative_to(ROOT))

    sprites["badge-circle-deco"] = badge_circle()
    sources["badge-circle-deco"] = "generated by build-atlas.py"

    canvas = Image.new("RGBA", ATLAS_SIZE, (0, 0, 0, 0))
    entries: list[dict] = []
    for name, position in PLACEMENTS.items():
        sprite = sprites[name]
        canvas.alpha_composite(sprite, position)
        entries.append(
            {
                "name": name,
                "x": position[0],
                "y": position[1],
                "width": sprite.width,
                "height": sprite.height,
                "source": sources[name],
            }
        )

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    canvas.save(ATLAS_PATH, format="PNG", optimize=True)
    MAP_PATH.write_text(
        json.dumps(
            {
                "atlas": ATLAS_PATH.name,
                "width": ATLAS_SIZE[0],
                "height": ATLAS_SIZE[1],
                "format": "RGBA PNG",
                "items": entries,
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    CSS_PATH.write_text(sprite_css(entries), encoding="utf-8")
    print(f"Wrote {ATLAS_PATH.relative_to(ROOT)}")
    print(f"Wrote {MAP_PATH.relative_to(ROOT)}")
    print(f"Wrote {CSS_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
