#!/usr/bin/env python3
"""Build a small local Jua WOFF2 containing only Korean glyphs used by OING."""

from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont


ROOT = Path(__file__).resolve().parents[1]
SOURCE = Path("/tmp/Jua-Regular.ttf")
OUTPUT = ROOT / "assets/fonts/Jua-Korean-Game.woff2"
CSS_OUTPUT = ROOT / "assets/fonts/Jua-Korean.css"
SCAN_PATHS = [ROOT / "index.html", ROOT / "css", ROOT / "js"]


def source_files():
    for path in SCAN_PATHS:
        if path.is_file():
            yield path
        elif path.is_dir():
            yield from path.rglob("*.css")
            yield from path.rglob("*.js")


# 주아체로 찍혀야 하는데 한글이 아닌 글자들.
#
# 서브셋이 한글만 담고 unicode-range도 한글만 걸어 두면, 같은 문장 안의
# 마침표·물음표·느낌표가 다음 폰트(Pretendard)로 떨어진다. 주아는 둥글고
# 말랑한 글씨체라 그 옆에 붙은 중성적인 문장부호가 튀어 보인다 - 실기기
# 제보의 "주아체여야 하는데 깨지는 글자"가 이것이다.
#
# 숫자는 일부러 뺐다. 점수·시계·타일 숫자가 전부 이 글씨체를 타므로
# 넣는 순간 게임 화면 전체의 숫자 인상이 바뀐다. 그건 따로 결정할 일이다.
EXTRA_CHARACTERS = ".,!?~'\"()%+-:/"


def is_korean(character: str) -> bool:
    code = ord(character)
    return (
        0x1100 <= code <= 0x11FF
        or 0x3130 <= code <= 0x318F
        or 0xA960 <= code <= 0xA97F
        or 0xAC00 <= code <= 0xD7AF
        or 0xD7B0 <= code <= 0xD7FF
    )


def main() -> None:
    if not SOURCE.exists():
        raise SystemExit(f"Missing official Jua source font: {SOURCE}")

    text = "".join(path.read_text(encoding="utf-8") for path in source_files())
    korean = sorted({character for character in text if is_korean(character)})
    if not korean:
        raise SystemExit("No Korean characters found")
    characters = korean + sorted(set(EXTRA_CHARACTERS))

    options = subset.Options()
    options.flavor = "woff2"
    options.layout_features = ["*"]
    options.name_IDs = [0, 1, 2, 3, 4, 5, 6]
    options.name_languages = [0x409]
    font = TTFont(SOURCE)
    worker = subset.Subsetter(options=options)
    worker.populate(text="".join(characters))
    worker.subset(font)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    font.flavor = "woff2"
    font.save(OUTPUT)

    unicode_ranges = ", ".join(f"U+{ord(character):04X}" for character in characters)
    CSS_OUTPUT.write_text(
        "/* Generated by tools/build-jua-subset.py from Google Fonts Jua (OFL-1.1). */\n"
        "@font-face {\n"
        '  font-family: "Oing Jua";\n'
        "  font-style: normal;\n"
        "  font-weight: 400;\n"
        "  font-display: swap;\n"
        '  src: url("./Jua-Korean-Game.woff2") format("woff2");\n'
        f"  unicode-range: {unicode_ranges};\n"
        "}\n",
        encoding="utf-8",
    )
    print(
        f"Built {OUTPUT.name}: {len(korean)} Korean glyphs "
        f"+ {len(set(EXTRA_CHARACTERS))} punctuation, {OUTPUT.stat().st_size} bytes"
    )


if __name__ == "__main__":
    main()
