#!/usr/bin/env python3
"""Build a small local Jua WOFF2 containing only Korean glyphs used by OING."""

from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont


ROOT = Path(__file__).resolve().parents[1]
SOURCE = Path("/tmp/Jua-Regular.ttf")
OUTPUT = ROOT / "assets/fonts/Jua-Korean-Game.woff2"
CSS_OUTPUT = ROOT / "assets/fonts/Jua-Korean.css"
SCAN_PATHS = [ROOT / "index.html", ROOT / "css", ROOT / "js"]


def source_files():
    for path in SCAN_PATHS:
        if path.is_file():
            yield path
        elif path.is_dir():
            yield from path.rglob("*.css")
            yield from path.rglob("*.js")


def is_korean(character: str) -> bool:
    code = ord(character)
    return (
        0x1100 <= code <= 0x11FF
        or 0x3130 <= code <= 0x318F
        or 0xA960 <= code <= 0xA97F
        or 0xAC00 <= code <= 0xD7AF
        or 0xD7B0 <= code <= 0xD7FF
    )


def main() -> None:
    if not SOURCE.exists():
        raise SystemExit(f"Missing official Jua source font: {SOURCE}")

    text = "".join(path.read_text(encoding="utf-8") for path in source_files())
    characters = sorted({character for character in text if is_korean(character)})
    if not characters:
        raise SystemExit("No Korean characters found")

    options = subset.Options()
    options.flavor = "woff2"
    options.layout_features = ["*"]
    options.name_IDs = [0, 1, 2, 3, 4, 5, 6]
    options.name_languages = [0x409]
    font = TTFont(SOURCE)
    worker = subset.Subsetter(options=options)
    worker.populate(text="".join(characters))
    worker.subset(font)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    font.flavor = "woff2"
    font.save(OUTPUT)

    unicode_ranges = ", ".join(f"U+{ord(character):04X}" for character in characters)
    CSS_OUTPUT.write_text(
        "/* Generated by tools/build-jua-subset.py from Google Fonts Jua (OFL-1.1). */\n"
        "@font-face {\n"
        '  font-family: "Oing Jua";\n'
        "  font-style: normal;\n"
        "  font-weight: 400;\n"
        "  font-display: swap;\n"
        '  src: url("./Jua-Korean-Game.woff2") format("woff2");\n'
        f"  unicode-range: {unicode_ranges};\n"
        "}\n",
        encoding="utf-8",
    )
    print(f"Built {OUTPUT.name}: {len(characters)} Korean glyphs, {OUTPUT.stat().st_size} bytes")


if __name__ == "__main__":
    main()
